### ISSUE TITLE
Bug: No module named 'web3.utils' 

### ISSUE THREAD

**Issue by arsenyjin** [oceanprotocol/provider-py#5]
While running `provider-py` locally ran into an error message:

```
Traceback (most recent call last):
  File "/home/x332/Projects/oceanprotocol/provider-py/venv/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/x332/Projects/oceanprotocol/provider-py/ocean_provider/run.py", line 13, in <module>
    from ocean_provider.routes import services
  File "/home/x332/Projects/oceanprotocol/provider-py/ocean_provider/routes.py", line 9, in <module>
    from ocean_provider.utils.basics import setup_network
  File "/home/x332/Projects/oceanprotocol/provider-py/ocean_provider/utils/basics.py", line 4, in <module>
    from ocean_keeper.contract_handler import ContractHandler
  File "/home/x332/Projects/oceanprotocol/provider-py/venv/lib/python3.6/site-packages/ocean_keeper/__init__.py", line 7, in <module>
    from .contract_base import ContractBase
  File "/home/x332/Projects/oceanprotocol/provider-py/venv/lib/python3.6/site-packages/ocean_keeper/contract_base.py", line 12, in <module>
    from web3.utils.threads import Timeout
ModuleNotFoundError: No module named 'web3.utils'
```

**Comment by arsenyjin** [comment]
Fixed with https://github.com/oceanprotocol/provider-py/commit/f9fff3ed6b7c24be886a81b18f05f7c657fbf796
