### ISSUE TITLE
Bug: the response {"size":0,"timeout":0} was thrown

### ISSUE THREAD

**Issue by arsenyjin** [oceanprotocol/provider-py#7]
While running lib-js [simple flow integration tests](https://github.com/oceanprotocol/lib-js/blob/feature/beta-version-phase-2/test/integration/Simpleflow.test.ts) on `ganache-cli` I'm running into the following issue on the `lib-js` side: 

```
  1) Simple flow
       #test
         Bob consumes dataset:
     Error: the response {"size":0,"timeout":0} was thrown, throw an Error :)
      at thrown2Error (/home/x332/Projects/oceanprotocol/lib-js/node_modules/mocha/lib/runner.js:1130:10)
      at Runner.fail (/home/x332/Projects/oceanprotocol/lib-js/node_modules/mocha/lib/runner.js:381:11)
      at /home/x332/Projects/oceanprotocol/lib-js/node_modules/mocha/lib/runner.js:771:18
      at done (/home/x332/Projects/oceanprotocol/lib-js/node_modules/mocha/lib/runnable.js:314:5)
      at /home/x332/Projects/oceanprotocol/lib-js/node_modules/mocha/lib/runnable.js:385:11
      at process._tickCallback (internal/process/next_tick.js:68:7)

``` 
and following response on the provider side:

```
2020-06-18 09:56:13 x332-TM1701 werkzeug[6511] INFO 127.0.0.1 - - [18/Jun/2020 09:56:13] "GET /api/v1/provider/services HTTP/1.1" 308 -
2020-06-18 09:56:13 x332-TM1701 werkzeug[6511] INFO 127.0.0.1 - - [18/Jun/2020 09:56:13] "GET /api/v1/provider/services/ HTTP/1.1" 400 -
```
I use the following as an env config:

```
(venv) x332@x332-TM1701:~/Projects/oceanprotocol/provider-py$ export PROVIDER_ADDRESS=0xb681A9850d07674392D788D234EF78de541cEA66
(venv) x332@x332-TM1701:~/Projects/oceanprotocol/provider-py$ export PROVIDER_KEY=0x2b9a2decd4b7b2b867a391dc9d5bfca1bb4f76a457dbf4b00d69df51ca76d8ec
(venv) x332@x332-TM1701:~/Projects/oceanprotocol/provider-py$ export CONFIG='{"File": /home/x332/Projects/oceanprotocol/test/test.file}'
(venv) x332@x332-TM1701:~/Projects/oceanprotocol/provider-py$ flask run --port=8030
```

where `PROVIDER_ADDRESS` and `PROVIDER_KEY` belong to `alice`

**Comment by arsenyjin** [comment]
fixed
